discord:
  clientToken: YOUR_DISCORD_TOKEN
  msgChannelId: DISCORD_CHANNEL_ID
gmail:
  credFile: credentials.json
  videoLabelName: videoCamNotifications
  choreLabelName: googleCalendarChores
    msgChannelOverride: DISCORD_CHANNEL_ID
